### ISSUE TITLE
Just telling u now Immortal only have 1 rank, not Immortal 1, 2 and 3; now it's just Immortal

### ISSUE THREAD

**Issue by BobbyESP** [sndrjhlncgr/VALORANT-Stream-Overlay#1]

**Comment by sndrjhlncgr** [comment]
oh thank you for that bobby! i nvr noticed that.  I'm might gonna fix that in the future cause I'm still fixing  my design for overlay hihi

**Comment by BobbyESP** [comment]
hihi. Ok dude. Lucky with that
